# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate threshold of maximum p-values across two studies to control FDR.
#' @param pa_in A numeric vector of p-values from study 1.
#' @param pb_in A numeric vector of p-values from study 2.
#' @param xi_in The estimates of proportions of three null components.
#' @param alpha_in The FDR level to control, default is 0.05.
#'
#' @return A list including the maximum of p-values and estimated threshold for FDR control.
#'
#' @export
jump_cutoff <- function(pa_in, pb_in, xi_in, alpha_in) {
    .Call(`_JUMP_jump_cutoff`, pa_in, pb_in, xi_in, alpha_in)
}

